### ISSUE TITLE
The dropping of txt files cannot be disabled.

### ISSUE THREAD

**Issue by DeveloperZvum** [Preston-Landers/pyuac#5]
Everytime I launch my python program it drops two txt files that I cannot figure out on how to disable it.

**Comment by Preston-Landers** [comment]
Can you clarify what are the names of these files and their contents?

**Comment by DeveloperZvum** [comment]
pyuac.stdout.tmp and pyuac.stderr.tmp one of them is empty the other is just printing the whole output of my original program.

**Comment by Preston-Landers** [comment]
The decorator function (`main_requires_admin`) does use these files to echo the output of the elevated process back to the console of the originating process. It does attempt to delete them when it's done, so this suggests something is interrupting that. 

One alternative is to not use `main_requires_admin` and instead just call the two core functions directly: `isUserAdmin` and `runAsAdmin`. This won't mess around with temporary files. You also won't gain the feature of automatically copying the output over to the original console, but you could implement that yourself if needed.

**Comment by DeveloperZvum** [comment]
thank you.
