### ISSUE TITLE
run python module not working with pyuac

### ISSUE THREAD

**Issue by wuyuanyi135** [Preston-Landers/pyuac#6]
Hi, If I want to run a script with `python -m the_module_name` it does not start it in the privileged mode.
For example, say we have a module `m.py` in the module `a`, the content off `m.py` is 
```
if __name__ == "__main__":
    if not pyuac.isUserAdmin():
        print("Re-launching as admin!")
        pyuac.runAsAdmin()
    else:
        with open("c:/executed.txt", "w") as f:
            f.write("written")
```
Then, if I run `python -m a.m`, it shows `Re-launching as admin!` but the privileged part is not executed. If I run this file as script (`python a/m.py`) it works properly.

Do you have any idea how to run the module in UAC mode?

**Comment by remram44** [comment]
Seems to work

**Comment by wuyuanyi135** [comment]
Yes. I realize it is because in UAC mode python could not import my library. Probably due to path
